// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"

typedef struct Color Color;
typedef struct EdgeInsets EdgeInsets;
typedef struct View View;
typedef struct App App;
typedef struct Window Window;
typedef struct Shadow Shadow;

struct Color {
    int64_t r;
    int64_t g;
    int64_t b;
    int64_t a;
};

struct EdgeInsets {
    double top;
    double right;
    double bottom;
    double left;
};

struct View {
    int64_t handle;
};

struct App {
    int64_t handle;
};

struct Window {
    int64_t handle;
};

struct Shadow {
    double offset_x;
    double offset_y;
    double blur;
    Color color;
};

extern void println(const char* s);
extern void print(const char* s);
extern Color color_background(void);
extern Color color_surface(void);
extern Color color_text(void);
extern Color color_primary(void);
extern Color color_accent(void);
extern Color color_rgba(int64_t r, int64_t g, int64_t b, int64_t a);
extern Color color_lighten(Color c, double amount);
extern Color color_darken(Color c, double amount);
extern Color color_blend(Color a, Color b, double t);
extern Color color_complement(Color c);
extern EdgeInsets insets_all(double value);
extern View vstack(double gap);
extern View hstack(double gap);
extern View text_view(const char* text);
extern View button_view(const char* label);
extern View spacer(void);
extern void view_set_background(View v, Color c);
extern void view_set_padding(View v, EdgeInsets p);
extern void view_set_corner_radius(View v, double r);
extern void view_set_shadow(View v, Shadow s);
extern void view_set_opacity(View v, double o);
extern void view_add_child(View parent, View child);
extern void text_set_font_size(View v, double size);
extern void text_set_font_weight(View v, int64_t weight);
extern void text_set_color(View v, Color c);
extern void button_set_style(View v, Color normal, Color hover, Color pressed);
extern void animate_fade_in(View v, double duration);
extern void animate_slide_in(View v, double from_x, double from_y, double duration);
extern void animate_pulse(View v, double duration);
extern void animate_bounce(View v, double duration);
extern Shadow shadow(double x, double y, double blur, Color color);
extern App app_new(const char* name);
extern Window app_create_window(App a, const char* title, int64_t w, int64_t h);
extern void app_run(App a);
extern void window_set_root(Window win, View v);

int64_t main(void);

int64_t main(void) {
    println("ReoxUI Animation Demo");
    println("=====================");
    App app = app_new("ReoxUI Demo");
    Window window = app_create_window(app, "Animation and Effects", 640, 480);
    Color primary = color_rgba(102, 126, 234, 255);
    Color secondary = color_rgba(240, 147, 251, 255);
    Color accent = color_rgba(129, 236, 236, 255);
    Color dark_bg = color_rgba(26, 26, 46, 255);
    Color card_bg = color_rgba(42, 42, 74, 255);
    View root = vstack(20.000000000000000);
    view_set_background(root, dark_bg);
    view_set_padding(root, insets_all(32.000000000000000));
    View title = text_view("Animation Showcase");
    text_set_font_size(title, 32.000000000000000);
    text_set_font_weight(title, 700);
    text_set_color(title, primary);
    view_add_child(root, title);
    View subtitle = text_view("Demonstrating ReoxUI transitions, colors, and effects");
    text_set_font_size(subtitle, 14.000000000000000);
    text_set_color(subtitle, color_rgba(180, 180, 200, 255));
    view_add_child(root, subtitle);
    View cards_row = hstack(16.000000000000000);
    View card1 = vstack(8.000000000000000);
    view_set_background(card1, card_bg);
    view_set_padding(card1, insets_all(20.000000000000000));
    view_set_corner_radius(card1, 16.000000000000000);
    view_set_shadow(card1, shadow(0.000000000000000, 8.000000000000000, 24.000000000000000, color_rgba(102, 126, 234, 100)));
    View card1_title = text_view("Transitions");
    text_set_font_size(card1_title, 18.000000000000000);
    text_set_font_weight(card1_title, 600);
    text_set_color(card1_title, primary);
    view_add_child(card1, card1_title);
    View card1_desc = text_view("Page animations");
    text_set_font_size(card1_desc, 12.000000000000000);
    text_set_color(card1_desc, color_rgba(200, 200, 220, 255));
    view_add_child(card1, card1_desc);
    view_add_child(cards_row, card1);
    View card2 = vstack(8.000000000000000);
    view_set_background(card2, card_bg);
    view_set_padding(card2, insets_all(20.000000000000000));
    view_set_corner_radius(card2, 16.000000000000000);
    view_set_shadow(card2, shadow(0.000000000000000, 8.000000000000000, 24.000000000000000, color_rgba(240, 147, 251, 100)));
    View card2_title = text_view("Color System");
    text_set_font_size(card2_title, 18.000000000000000);
    text_set_font_weight(card2_title, 600);
    text_set_color(card2_title, secondary);
    view_add_child(card2, card2_title);
    View card2_desc = text_view("HSL, LAB, LCH");
    text_set_font_size(card2_desc, 12.000000000000000);
    text_set_color(card2_desc, color_rgba(200, 200, 220, 255));
    view_add_child(card2, card2_desc);
    view_add_child(cards_row, card2);
    View card3 = vstack(8.000000000000000);
    view_set_background(card3, card_bg);
    view_set_padding(card3, insets_all(20.000000000000000));
    view_set_corner_radius(card3, 16.000000000000000);
    view_set_shadow(card3, shadow(0.000000000000000, 8.000000000000000, 24.000000000000000, color_rgba(129, 236, 236, 100)));
    View card3_title = text_view("Lighting");
    text_set_font_size(card3_title, 18.000000000000000);
    text_set_font_weight(card3_title, 600);
    text_set_color(card3_title, accent);
    view_add_child(card3, card3_title);
    View card3_desc = text_view("Dynamic glow");
    text_set_font_size(card3_desc, 12.000000000000000);
    text_set_color(card3_desc, color_rgba(200, 200, 220, 255));
    view_add_child(card3, card3_desc);
    view_add_child(cards_row, card3);
    view_add_child(root, cards_row);
    View buttons = hstack(12.000000000000000);
    View btn_animate = button_view("Animate");
    button_set_style(btn_animate, primary, color_lighten(primary, 0.200000000000000), color_darken(primary, 0.200000000000000));
    view_add_child(buttons, btn_animate);
    View btn_particles = button_view("Particles");
    button_set_style(btn_particles, secondary, color_lighten(secondary, 0.200000000000000), color_darken(secondary, 0.200000000000000));
    view_add_child(buttons, btn_particles);
    View btn_glow = button_view("Glow Effect");
    button_set_style(btn_glow, accent, color_lighten(accent, 0.200000000000000), color_darken(accent, 0.200000000000000));
    view_add_child(buttons, btn_glow);
    view_add_child(root, buttons);
    View footer = text_view("ReoxUI for NeolyxOS - All features production-ready");
    text_set_font_size(footer, 11.000000000000000);
    text_set_color(footer, color_rgba(120, 120, 140, 255));
    view_add_child(root, footer);
    window_set_root(window, root);
    println("UI created with:");
    println("  - Custom color palette");
    println("  - Card shadows with glow");
    println("  - Animated buttons");
    println("");
    println("Running application...");
    app_run(app);
    println("Demo closed.");
    return 0;
}

