// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"

typedef struct Color Color;
typedef struct EdgeInsets EdgeInsets;
typedef struct Border Border;
typedef struct Shadow Shadow;
typedef struct View View;
typedef struct App App;
typedef struct Window Window;

struct Color {
    int64_t r;
    int64_t g;
    int64_t b;
    int64_t a;
};

struct EdgeInsets {
    double top;
    double right;
    double bottom;
    double left;
};

struct Border {
    double width;
    Color color;
    int64_t style;
};

struct Shadow {
    double offset_x;
    double offset_y;
    double blur;
    Color color;
};

struct View {
    int64_t handle;
};

struct App {
    int64_t handle;
};

struct Window {
    int64_t handle;
};

extern void println(const char* s);
extern void print(const char* s);
extern void print_int(int64_t n);
extern Color color_background(void);
extern Color color_surface(void);
extern Color color_text(void);
extern Color color_primary(void);
extern Color color_accent(void);
extern Color color_rgba(int64_t r, int64_t g, int64_t b, int64_t a);
extern Color color_lighten(Color c, double amount);
extern Color color_darken(Color c, double amount);
extern EdgeInsets insets_all(double value);
extern EdgeInsets insets_symmetric(double v, double h);
extern Border border(double width, Color color);
extern Shadow shadow(double x, double y, double blur, Color color);
extern View vstack(double gap);
extern View hstack(double gap);
extern View text_view(const char* text);
extern View button_view(const char* label);
extern void view_set_background(View v, Color c);
extern void view_set_padding(View v, EdgeInsets p);
extern void view_set_corner_radius(View v, double r);
extern void view_set_shadow(View v, Shadow s);
extern void view_set_border(View v, Border b);
extern void view_add_child(View parent, View child);
extern void text_set_font_size(View v, double size);
extern void text_set_font_weight(View v, int64_t weight);
extern void text_set_color(View v, Color c);
extern void button_set_style(View v, Color normal, Color hover, Color pressed);
extern App app_new(const char* name);
extern Window app_create_window(App a, const char* title, int64_t w, int64_t h);
extern void app_run(App a);
extern void window_set_root(Window win, View v);

int64_t main(void);

int64_t main(void) {
    println("Building NeolyxOS Display Settings UI...");
    App app = app_new("NeolyxOS Settings");
    Window window = app_create_window(app, "Display Settings", 800, 600);
    View root = vstack(16.000000000000000);
    view_set_background(root, color_background());
    view_set_padding(root, insets_all(24.000000000000000));
    View header = text_view("Display Settings");
    text_set_font_size(header, 28.000000000000000);
    text_set_font_weight(header, 700);
    text_set_color(header, color_text());
    view_add_child(root, header);
    View resolution_card = vstack(12.000000000000000);
    view_set_background(resolution_card, color_surface());
    view_set_padding(resolution_card, insets_all(16.000000000000000));
    view_set_corner_radius(resolution_card, 12.000000000000000);
    view_set_shadow(resolution_card, shadow(0.000000000000000, 4.000000000000000, 16.000000000000000, color_rgba(0, 0, 0, 80)));
    View res_title = text_view("Resolution");
    text_set_font_size(res_title, 18.000000000000000);
    text_set_font_weight(res_title, 600);
    view_add_child(resolution_card, res_title);
    View res_value = text_view("3840 x 2160 @ 144Hz");
    text_set_color(res_value, color_primary());
    view_add_child(resolution_card, res_value);
    view_add_child(root, resolution_card);
    View brightness_card = vstack(12.000000000000000);
    view_set_background(brightness_card, color_surface());
    view_set_padding(brightness_card, insets_all(16.000000000000000));
    view_set_corner_radius(brightness_card, 12.000000000000000);
    view_set_border(brightness_card, border(1.000000000000000, color_rgba(255, 255, 255, 30)));
    View bright_title = text_view("Brightness");
    text_set_font_size(bright_title, 18.000000000000000);
    text_set_font_weight(bright_title, 600);
    view_add_child(brightness_card, bright_title);
    View bright_value = text_view("80%");
    text_set_color(bright_value, color_text());
    view_add_child(brightness_card, bright_value);
    view_add_child(root, brightness_card);
    View color_card = hstack(16.000000000000000);
    view_set_background(color_card, color_surface());
    view_set_padding(color_card, insets_all(16.000000000000000));
    view_set_corner_radius(color_card, 12.000000000000000);
    View srgb_btn = button_view("sRGB");
    View p3_btn = button_view("Display P3");
    View hdr_btn = button_view("HDR");
    view_add_child(color_card, srgb_btn);
    view_add_child(color_card, p3_btn);
    view_add_child(color_card, hdr_btn);
    view_add_child(root, color_card);
    View apply_btn = button_view("Apply Changes");
    button_set_style(apply_btn, color_accent(), color_lighten(color_accent(), 0.150000000000000), color_darken(color_accent(), 0.150000000000000));
    view_add_child(root, apply_btn);
    window_set_root(window, root);
    println("UI built successfully!");
    println("Launching app...");
    app_run(app);
    println("Display Settings closed.");
    return 0;
}

