// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"

typedef struct Color Color;
typedef struct EdgeInsets EdgeInsets;
typedef struct Border Border;
typedef struct Shadow Shadow;
typedef struct View View;
typedef struct App App;
typedef struct Window Window;
typedef struct StateInt StateInt;
typedef struct StateBool StateBool;

struct Color {
    int64_t r;
    int64_t g;
    int64_t b;
    int64_t a;
};

struct EdgeInsets {
    double top;
    double right;
    double bottom;
    double left;
};

struct Border {
    double width;
    Color color;
    int64_t style;
};

struct Shadow {
    double offset_x;
    double offset_y;
    double blur;
    Color color;
};

struct View {
    int64_t handle;
};

struct App {
    int64_t handle;
};

struct Window {
    int64_t handle;
};

struct StateInt {
    int64_t value;
    int64_t id;
};

struct StateBool {
    bool value;
    int64_t id;
};

extern void println(const char* s);
extern void print(const char* s);
extern void print_int(int64_t n);
extern Color color_background(void);
extern Color color_surface(void);
extern Color color_text(void);
extern Color color_primary(void);
extern Color color_accent(void);
extern Color color_success(void);
extern Color color_warning(void);
extern Color color_error(void);
extern Color color_rgba(int64_t r, int64_t g, int64_t b, int64_t a);
extern Color color_lighten(Color c, double amount);
extern Color color_darken(Color c, double amount);
extern EdgeInsets insets_all(double value);
extern Border border(double width, Color c);
extern Shadow shadow(double x, double y, double blur, Color c);
extern View vstack(double gap);
extern View hstack(double gap);
extern View scroll_view(void);
extern View spacer(void);
extern View divider(void);
extern View grid_view(int64_t cols, double gap);
extern View text_view(const char* text);
extern View button_view(const char* label);
extern View slider_view(double min_val, double max_val, double value);
extern View toggle_view(const char* label, bool on);
extern View icon_view(const char* name);
extern void view_set_background(View v, Color c);
extern void view_set_padding(View v, EdgeInsets p);
extern void view_set_corner_radius(View v, double r);
extern void view_set_shadow(View v, Shadow s);
extern void view_set_border(View v, Border b);
extern void view_add_child(View parent, View child);
extern void view_set_opacity(View v, double alpha);
extern void text_set_font_size(View v, double size);
extern void text_set_font_weight(View v, int64_t weight);
extern void text_set_color(View v, Color c);
extern void button_set_style(View v, Color normal, Color hover, Color pressed);
extern App app_new(const char* name);
extern Window app_create_window(App app, const char* title, int64_t w, int64_t h);
extern void app_run(App app);
extern void window_set_root(Window win, View v);
extern StateInt state_int(int64_t initial);
extern StateBool state_bool(bool initial);
extern int64_t state_get_int(StateInt s);
extern bool state_get_bool(StateBool s);
extern const char* platform_name(void);
extern int64_t screen_width(void);
extern int64_t screen_height(void);
extern int64_t set_interval(int64_t callback_id, int64_t interval_ms);

View create_card(const char* title);
View create_stat_widget(const char* label, const char* value, Color c);
View create_progress_bar(double percent, Color c);
int64_t main(void);

View create_card(const char* title) {
    View card = vstack(8.000000000000000);
    view_set_background(card, color_surface());
    view_set_padding(card, insets_all(16.000000000000000));
    view_set_corner_radius(card, 12.000000000000000);
    view_set_shadow(card, shadow(0.000000000000000, 2.000000000000000, 8.000000000000000, color_rgba(0, 0, 0, 60)));
    View header = text_view(title);
    text_set_font_size(header, 16.000000000000000);
    text_set_font_weight(header, 600);
    text_set_color(header, color_text());
    view_add_child(card, header);
    return card;
}

View create_stat_widget(const char* label, const char* value, Color c) {
    View stat = vstack(4.000000000000000);
    view_set_background(stat, color_rgba(0, 0, 0, 0));
    View val_text = text_view(value);
    text_set_font_size(val_text, 28.000000000000000);
    text_set_font_weight(val_text, 700);
    text_set_color(val_text, c);
    view_add_child(stat, val_text);
    View lbl_text = text_view(label);
    text_set_font_size(lbl_text, 12.000000000000000);
    text_set_color(lbl_text, color_rgba(174, 174, 178, 255));
    view_add_child(stat, lbl_text);
    return stat;
}

View create_progress_bar(double percent, Color c) {
    View container = hstack(0.000000000000000);
    view_set_background(container, color_rgba(60, 60, 60, 255));
    view_set_corner_radius(container, 4.000000000000000);
    View fill = spacer();
    view_set_background(fill, c);
    view_set_corner_radius(fill, 4.000000000000000);
    view_set_opacity(fill, (percent / 100.000000000000000));
    view_add_child(container, fill);
    return container;
}

int64_t main(void) {
    println("=== REOX System Monitor ===");
    println("");
    App app = app_new("System Monitor");
    Window window = app_create_window(app, "NeolyxOS System Monitor", 800, 600);
    View root = vstack(16.000000000000000);
    view_set_background(root, color_background());
    view_set_padding(root, insets_all(24.000000000000000));
    View header = hstack(12.000000000000000);
    View logo = icon_view("neolyx-logo");
    view_add_child(header, logo);
    View title = text_view("System Monitor");
    text_set_font_size(title, 24.000000000000000);
    text_set_font_weight(title, 700);
    text_set_color(title, color_text());
    view_add_child(header, title);
    view_add_child(header, spacer());
    View platform_label = text_view(platform_name());
    text_set_color(platform_label, color_primary());
    view_add_child(header, platform_label);
    view_add_child(root, header);
    view_add_child(root, divider());
    View stats_grid = grid_view(4, 16.000000000000000);
    View cpu_card = create_card("CPU");
    View cpu_stat = create_stat_widget("Usage", "42%", color_primary());
    view_add_child(cpu_card, cpu_stat);
    View cpu_bar = create_progress_bar(42.000000000000000, color_primary());
    view_add_child(cpu_card, cpu_bar);
    view_add_child(stats_grid, cpu_card);
    View mem_card = create_card("Memory");
    View mem_stat = create_stat_widget("Used", "8.2 GB", color_success());
    view_add_child(mem_card, mem_stat);
    View mem_bar = create_progress_bar(68.000000000000000, color_success());
    view_add_child(mem_card, mem_bar);
    view_add_child(stats_grid, mem_card);
    View disk_card = create_card("Disk");
    View disk_stat = create_stat_widget("Used", "256 GB", color_warning());
    view_add_child(disk_card, disk_stat);
    View disk_bar = create_progress_bar(51.000000000000000, color_warning());
    view_add_child(disk_card, disk_bar);
    view_add_child(stats_grid, disk_card);
    View net_card = create_card("Network");
    View net_stat = create_stat_widget("Speed", "125 Mbps", color_accent());
    view_add_child(net_card, net_stat);
    view_add_child(stats_grid, net_card);
    view_add_child(root, stats_grid);
    View proc_card = create_card("Running Processes");
    View proc_list = scroll_view();
    View proc1 = hstack(8.000000000000000);
    View p1_name = text_view("zepra-browser");
    View p1_cpu = text_view("12.3%");
    text_set_color(p1_cpu, color_primary());
    view_add_child(proc1, p1_name);
    view_add_child(proc1, spacer());
    view_add_child(proc1, p1_cpu);
    view_add_child(proc_list, proc1);
    View proc2 = hstack(8.000000000000000);
    View p2_name = text_view("neolyx-compositor");
    View p2_cpu = text_view("8.7%");
    text_set_color(p2_cpu, color_primary());
    view_add_child(proc2, p2_name);
    view_add_child(proc2, spacer());
    view_add_child(proc2, p2_cpu);
    view_add_child(proc_list, proc2);
    View proc3 = hstack(8.000000000000000);
    View p3_name = text_view("reox-runtime");
    View p3_cpu = text_view("2.1%");
    text_set_color(p3_cpu, color_success());
    view_add_child(proc3, p3_name);
    view_add_child(proc3, spacer());
    view_add_child(proc3, p3_cpu);
    view_add_child(proc_list, proc3);
    view_add_child(proc_card, proc_list);
    view_add_child(root, proc_card);
    View actions = hstack(12.000000000000000);
    view_add_child(actions, spacer());
    View refresh_btn = button_view("Refresh");
    button_set_style(refresh_btn, color_primary(), color_lighten(color_primary(), 0.100000000000000), color_darken(color_primary(), 0.100000000000000));
    view_add_child(actions, refresh_btn);
    View kill_btn = button_view("End Process");
    button_set_style(kill_btn, color_error(), color_lighten(color_error(), 0.100000000000000), color_darken(color_error(), 0.100000000000000));
    view_add_child(actions, kill_btn);
    view_add_child(root, actions);
    window_set_root(window, root);
    println("");
    println("UI Structure complete!");
    app_run(app);
    return 0;
}

