// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"
#include "reox_nxrender_bridge.h"

typedef struct Color Color;
typedef struct EdgeInsets EdgeInsets;
typedef struct View View;
typedef struct App App;
typedef struct Window Window;
typedef struct Shadow Shadow;

struct Color {
    int64_t r;
    int64_t g;
    int64_t b;
    int64_t a;
};

struct EdgeInsets {
    double top;
    double right;
    double bottom;
    double left;
};

struct View {
    int64_t handle;
};

struct App {
    int64_t handle;
};

struct Window {
    int64_t handle;
};

struct Shadow {
    double offset_x;
    double offset_y;
    double blur;
    Color color;
};

extern void println(const char* s);
extern void print(const char* s);
extern const char* int_to_string(int64_t i);
extern const char* float_to_string(double f);
extern const char* string_concat(const char* a, const char* b);
extern bool string_eq(const char* a, const char* b);
extern void append_file(const char* path, const char* content);
extern Color color_rgba(int64_t r, int64_t g, int64_t b, int64_t a);
extern Color color_background(void);
extern Color color_surface(void);
extern Color color_text(void);
extern Color color_primary(void);
extern Color color_secondary(void);
extern Color color_accent(void);
extern EdgeInsets insets_all(double value);
extern Shadow shadow(double x, double y, double blur, Color c);
extern View vstack(double gap);
extern View hstack(double gap);
extern View grid_view(int64_t cols, double gap);
extern View spacer(void);
extern View text_view(const char* text);
extern View button_view(const char* label);
extern View toggle_view(const char* label, bool on);
extern void view_set_background(View v, Color c);
extern void view_set_padding(View v, EdgeInsets p);
extern void view_set_corner_radius(View v, double r);
extern void view_set_shadow(View v, Shadow s);
extern void view_add_child(View parent, View child);
extern void view_set_size(View v, double w, double h);
extern void text_view_set_text(View v, const char* text);
extern void text_set_font_size(View v, double size);
extern void text_set_font_weight(View v, int64_t weight);
extern void text_set_color(View v, Color c);
extern void text_set_align(View v, int64_t align);
extern void button_set_style(View v, Color normal, Color hover, Color pressed);
extern void button_set_on_click(View v, int64_t callback_id);
extern App app_new(const char* name);
extern Window app_create_window(App app, const char* title, int64_t w, int64_t h);
extern void app_run(App app);
extern void window_set_root(Window win, View v);
extern const char* get_display(void);
extern void set_display(const char* s);
extern double get_accumulator(void);
extern void set_accumulator(double v);
extern const char* get_pending_op(void);
extern void set_pending_op(const char* s);
extern bool get_new_entry(void);
extern void set_new_entry(bool v);
extern bool get_settings_visible(void);
extern void set_settings_visible(bool v);
extern int64_t get_display_label_handle(void);
extern void set_display_label_handle(int64_t h);
extern int64_t get_root_view_handle(void);
extern void set_root_view_handle(int64_t h);
extern Color get_button_color_wrapper(bool is_op, bool is_action, int64_t state);

void update_ui(void);
void save_history(const char* entry);
void set_op(const char* op);
void on_add(void);
void on_sub(void);
void on_mul(void);
void on_div(void);
void on_eq(void);
void on_clear(void);
void clear_all(void);
void append_digit(const char* digit);
void on_click_handler(int64_t id);
View create_button(const char* label, bool is_op, bool is_action, int64_t id);
View create_keypad(void);
View create_settings(void);
int64_t main(void);

void update_ui(void) {
    int64_t handle = get_display_label_handle();
    if ((handle != -1)) {
        View v = (View){.handle = handle};
        text_view_set_text(v, get_display());
    }
}

void save_history(const char* entry) {
    append_file("history.txt", entry);
    append_file("history.txt", "\n");
}

void set_op(const char* op) {
    set_pending_op(op);
    set_new_entry(true);
}

void on_add(void) {
    set_op("+");
}

void on_sub(void) {
    set_op("-");
}

void on_mul(void) {
    set_op("*");
}

void on_div(void) {
    set_op("/");
}

void on_eq(void) {
    set_new_entry(true);
    set_display("Result");
    update_ui();
    save_history("Calculation performed");
}

void on_clear(void) {
    clear_all();
}

void clear_all(void) {
    set_display("0");
    set_accumulator(0.000000000000000);
    set_pending_op("");
    set_new_entry(true);
    update_ui();
}

void append_digit(const char* digit) {
    const char* current = get_display();
    set_display(string_concat(current, digit));
    update_ui();
}

void on_click_handler(int64_t id) {
    println("Button clicked!");
}

View create_button(const char* label, bool is_op, bool is_action, int64_t id) {
    View btn = button_view(label);
    Color base_color = get_button_color_wrapper(is_op, is_action, 0);
    Color hover_color = get_button_color_wrapper(is_op, is_action, 1);
    Color pressed_color = color_rgba(30, 30, 30, 255);
    button_set_style(btn, base_color, hover_color, pressed_color);
    view_set_corner_radius(btn, 8.000000000000000);
    button_set_on_click(btn, id);
    return btn;
}

View create_keypad(void) {
    View keypad = grid_view(4, 12.000000000000000);
    view_add_child(keypad, create_button("C", true, false, 201));
    view_add_child(keypad, create_button("+/-", true, false, 202));
    view_add_child(keypad, create_button("%", true, false, 203));
    view_add_child(keypad, create_button("/", true, false, 204));
    view_add_child(keypad, create_button("7", false, false, 107));
    view_add_child(keypad, create_button("8", false, false, 108));
    view_add_child(keypad, create_button("9", false, false, 109));
    view_add_child(keypad, create_button("x", true, false, 205));
    view_add_child(keypad, create_button("4", false, false, 104));
    view_add_child(keypad, create_button("5", false, false, 105));
    view_add_child(keypad, create_button("6", false, false, 106));
    view_add_child(keypad, create_button("-", true, false, 206));
    view_add_child(keypad, create_button("1", false, false, 101));
    view_add_child(keypad, create_button("2", false, false, 102));
    view_add_child(keypad, create_button("3", false, false, 103));
    view_add_child(keypad, create_button("+", true, false, 207));
    view_add_child(keypad, create_button("0", false, false, 100));
    view_add_child(keypad, create_button(".", false, false, 110));
    view_add_child(keypad, create_button("=", false, true, 208));
    view_add_child(keypad, create_button("H", false, false, 300));
    return keypad;
}

View create_settings(void) {
    View v = reox_vstack(16.000000000000000);
    view_set_background(v, (rx_color){44, 44, 46, 255});
    view_set_padding(v, insets_all(20.000000000000000));
    view_set_corner_radius(v, 12.000000000000000);
    View title = text_view("Settings");
    text_set_font_size(title, 20.000000000000000);
    view_add_child(v, title);
    View sound_toggle = toggle_view("Sound Effects", true);
    view_add_child(v, sound_toggle);
    View haptic_toggle = toggle_view("Haptic Feedback", true);
    view_add_child(v, haptic_toggle);
    View theme_toggle = toggle_view("High Contrast", false);
    view_add_child(v, theme_toggle);
    return v;
}

int64_t main(void) {
    println("Starting Reox Calculator...");
    App app = app_new("Calculator");
    Window window = app_create_window(app, "Calculator", 320, 520);
    View root_view = reox_vstack(16.000000000000000);
    view_set_background(root_view, (rx_color){28, 28, 30, 255});
    view_set_padding(root_view, insets_all(20.000000000000000));
    set_root_view_handle(root_view.handle);
    View display_container = reox_vstack(0.000000000000000);
    view_set_background(display_container, color_rgba(40, 40, 40, 255));
    view_set_corner_radius(display_container, 12.000000000000000);
    view_set_padding(display_container, insets_all(16.000000000000000));
    View display_label = text_view("0");
    text_set_font_size(display_label, 48.000000000000000);
    text_set_font_weight(display_label, 300);
    text_set_align(display_label, 2);
    text_set_color(display_label, (rx_color){255, 255, 255, 255});
    set_display_label_handle(display_label.handle);
    view_add_child(display_container, display_label);
    view_add_child(root_view, display_container);
    View main_layout = create_keypad();
    view_add_child(root_view, main_layout);
    view_add_child(root_view, spacer());
    View settings_btn = button_view("Settings");
    button_set_style(settings_btn, (rx_color){44, 44, 46, 255}, (rx_color){255, 255, 255, 255}, (rx_color){0, 122, 255, 255});
    view_add_child(root_view, settings_btn);
    View settings_panel = create_settings();
    view_add_child(root_view, settings_panel);
    save_history("Calculator Started");
    window_set_root(window, root_view);
    println("Calculator UI Ready");
    app_run(app);
    return 0;
}

