// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"
#include "reox_nxrender_bridge.h"

extern void println(const char* s);

int64_t main(void);

int64_t main(void) {
    println("Hello Minimal");
    return 0;
}

