// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"
#include "reox_nxrender_bridge.h"

typedef struct Color Color;
typedef struct View View;
typedef struct App App;
typedef struct Window Window;
typedef struct EdgeInsets EdgeInsets;
typedef struct Shadow Shadow;
typedef struct Animation Animation;

struct Color {
    int64_t r;
    int64_t g;
    int64_t b;
    int64_t a;
};

struct View {
    int64_t handle;
};

struct App {
    int64_t handle;
};

struct Window {
    int64_t handle;
};

struct EdgeInsets {
    double top;
    double right;
    double bottom;
    double left;
};

struct Shadow {
    double offset_x;
    double offset_y;
    double blur;
    Color color;
};

struct Animation {
    int64_t id;
};

extern void println(const char* s);
extern void print(const char* s);
extern Color color_rgba(int64_t r, int64_t g, int64_t b, int64_t a);
extern Color color_lighten(Color c, double amount);
extern Color color_darken(Color c, double amount);
extern Color color_blend(Color a, Color b, double t);
extern EdgeInsets insets_all(double value);
extern Shadow shadow(double x, double y, double blur, Color color);
extern View vstack(double gap);
extern View hstack(double gap);
extern View spacer(void);
extern View text_view(const char* text);
extern View button_view(const char* label);
extern void view_set_background(View v, Color c);
extern void view_set_padding(View v, EdgeInsets p);
extern void view_set_corner_radius(View v, double r);
extern void view_set_shadow(View v, Shadow s);
extern void view_set_opacity(View v, double o);
extern void view_add_child(View parent, View child);
extern void text_set_font_size(View v, double size);
extern void text_set_font_weight(View v, int64_t weight);
extern void text_set_color(View v, Color c);
extern void button_set_style(View v, Color normal, Color hover, Color pressed);
extern Animation rx_view_fade_in(View v, double duration);
extern Animation rx_view_fade_out(View v, double duration);
extern Animation rx_view_slide_in(View v, double from_x, double from_y, double duration);
extern Animation rx_view_bounce(View v, double duration);
extern Animation rx_view_pulse(View v, double duration);
extern Animation rx_view_shake(View v, double duration);
extern void rx_animator_update(double dt);
extern App app_new(const char* name);
extern Window app_create_window(App a, const char* title, int64_t w, int64_t h);
extern void app_run(App a);
extern void window_set_root(Window win, View v);
extern void delay_ms(int64_t ms);

View build_animated_card(const char* title, const char* description, Color primary);
int64_t main(void);

View build_animated_card(const char* title, const char* description, Color primary) {
    View card = vstack(8.000000000000000);
    view_set_background(card, color_rgba(40, 42, 54, 255));
    view_set_padding(card, insets_all(20.000000000000000));
    view_set_corner_radius(card, 16.000000000000000);
    view_set_shadow(card, shadow(0.000000000000000, 8.000000000000000, 24.000000000000000, color_rgba(0, 0, 0, 100)));
    View title_view = text_view(title);
    text_set_font_size(title_view, 18.000000000000000);
    text_set_font_weight(title_view, 600);
    text_set_color(title_view, primary);
    view_add_child(card, title_view);
    View desc_view = text_view(description);
    text_set_font_size(desc_view, 12.000000000000000);
    text_set_color(desc_view, color_rgba(180, 180, 180, 255));
    view_add_child(card, desc_view);
    return card;
}

int64_t main(void) {
    println("========================================");
    println("REOX Animation Visual Test");
    println("========================================");
    println("");
    App app = app_new("REOX Animation Test");
    Window window = app_create_window(app, "Animation Demo", 800, 600);
    Color bg = color_rgba(26, 27, 38, 255);
    Color purple = color_rgba(139, 92, 246, 255);
    Color pink = color_rgba(236, 72, 153, 255);
    Color cyan = color_rgba(34, 211, 238, 255);
    Color green = color_rgba(34, 197, 94, 255);
    View root = vstack(24.000000000000000);
    view_set_background(root, bg);
    view_set_padding(root, insets_all(32.000000000000000));
    View title = text_view("Animation System Test");
    text_set_font_size(title, 28.000000000000000);
    text_set_font_weight(title, 700);
    text_set_color(title, color_rgba(255, 255, 255, 255));
    view_add_child(root, title);
    View subtitle = text_view("Demonstrating REOX animation capabilities");
    text_set_font_size(subtitle, 14.000000000000000);
    text_set_color(subtitle, color_rgba(160, 160, 170, 255));
    view_add_child(root, subtitle);
    View cards = hstack(16.000000000000000);
    View fade_card = build_animated_card("Fade", "Opacity transitions", purple);
    view_add_child(cards, fade_card);
    View slide_card = build_animated_card("Slide", "Position animations", pink);
    view_add_child(cards, slide_card);
    View bounce_card = build_animated_card("Bounce", "Spring physics", cyan);
    view_add_child(cards, bounce_card);
    View pulse_card = build_animated_card("Pulse", "Scale effects", green);
    view_add_child(cards, pulse_card);
    view_add_child(root, cards);
    View buttons = hstack(12.000000000000000);
    View btn1 = button_view("Fade In");
    button_set_style(btn1, purple, color_lighten(purple, 0.200000000000000), color_darken(purple, 0.200000000000000));
    view_add_child(buttons, btn1);
    View btn2 = button_view("Slide In");
    button_set_style(btn2, pink, color_lighten(pink, 0.200000000000000), color_darken(pink, 0.200000000000000));
    view_add_child(buttons, btn2);
    View btn3 = button_view("Bounce");
    button_set_style(btn3, cyan, color_lighten(cyan, 0.200000000000000), color_darken(cyan, 0.200000000000000));
    view_add_child(buttons, btn3);
    View btn4 = button_view("Pulse");
    button_set_style(btn4, green, color_lighten(green, 0.200000000000000), color_darken(green, 0.200000000000000));
    view_add_child(buttons, btn4);
    view_add_child(root, buttons);
    View footer = text_view("REOX UI Framework for NeolyxOS");
    text_set_font_size(footer, 11.000000000000000);
    text_set_color(footer, color_rgba(100, 100, 110, 255));
    view_add_child(root, footer);
    window_set_root(window, root);
    println("Applying entrance animations...");
    rx_view_fade_in(title, 0.500000000000000);
    rx_view_slide_in(fade_card, -50.000000000000000, 0.000000000000000, 0.400000000000000);
    rx_view_slide_in(slide_card, 0.000000000000000, 50.000000000000000, 0.500000000000000);
    rx_view_slide_in(bounce_card, 50.000000000000000, 0.000000000000000, 0.600000000000000);
    rx_view_slide_in(pulse_card, 0.000000000000000, -50.000000000000000, 0.700000000000000);
    rx_view_bounce(btn1, 0.300000000000000);
    rx_view_bounce(btn2, 0.350000000000000);
    rx_view_bounce(btn3, 0.400000000000000);
    rx_view_bounce(btn4, 0.450000000000000);
    println("Animations queued!");
    println("");
    println("Running application event loop...");
    app_run(app);
    println("Animation test complete.");
    return 0;
}

