// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef struct Point Point;

struct Point {
    int64_t x;
    int64_t y;
};

int64_t add(int64_t a, int64_t b);
int64_t distance(Point p1, Point p2);
int64_t main(void);

int64_t add(int64_t a, int64_t b) {
    return (a + b);
}

int64_t distance(Point p1, Point p2) {
    int64_t dx = (p2.x - p1.x);
    int64_t dy = (p2.y - p1.y);
    return ((dx * dx) + (dy * dy));
}

int64_t main(void) {
    int64_t x = 10;
    int64_t y = 20;
    int64_t sum = add(x, y);
    if ((sum > 25)) {
        println("Sum is greater than 25");
    } else {
        println("Sum is 25 or less");
    }
    Point p1 = (Point){.x = 0, .y = 0};
    Point p2 = (Point){.x = 3, .y = 4};
    int64_t dist = distance(p1, p2);
    return 0;
}

