// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"
#include "reox_nxrender_bridge.h"

typedef struct Color Color;

struct Color {
    int64_t r;
    int64_t g;
    int64_t b;
    int64_t a;
};

extern void println(const char* s);
extern Color color_rgba(int64_t r, int64_t g, int64_t b, int64_t a);

int64_t main(void);

int64_t main(void) {
    println("=== REOX Simple UI Test ===");
    println("Test 1: Creating colors...");
    Color red = color_rgba(255, 0, 0, 255);
    Color green = color_rgba(0, 255, 0, 255);
    Color blue = color_rgba(0, 0, 255, 255);
    println("  Colors created successfully!");
    println("Test 2: Basic arithmetic...");
    int64_t a = 10;
    int64_t b = 20;
    int64_t sum = (a + b);
    println("  Arithmetic working!");
    println("Test 3: Conditionals...");
    if ((sum > 25)) {
        println("  Sum > 25: PASS");
    } else {
        println("  Sum <= 25: UNEXPECTED");
    }
    println("Test 4: Loop...");
    int64_t i = 0;
    while ((i < 3)) {
        println("  Loop iteration");
        i = (i + 1);
    }
    println("  Loop complete!");
    println("");
    println("=== All simple tests passed! ===");
    return 0;
}

