// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"

int64_t main(void);

int64_t main(void) {
    println("Hello from REOX!");
    int64_t x = 42;
    int64_t y = 8;
    int64_t sum = (x + y);
    println("Testing arithmetic:");
    print_int(sum);
    println("");
    return 0;
}

