// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "reox_runtime.h"
#include "reox_nxrender_bridge.h"

typedef struct Direction Direction;
typedef struct Shape Shape;
typedef struct Color Color;
typedef struct Button Button;

typedef int64_t Dimension;
static const int64_t MAX_WIDTH = 800;
static const int64_t MAX_HEIGHT = 600;
typedef enum {
    DIRECTION_UP,
    DIRECTION_DOWN,
    DIRECTION_LEFT,
    DIRECTION_RIGHT
} Direction_Tag;

struct Direction {
    Direction_Tag tag;
};

typedef enum {
    SHAPE_CIRCLE,
    SHAPE_RECT
} Shape_Tag;

struct Shape {
    Shape_Tag tag;
    union {
        struct {
            double radius;
        } circle;
        struct {
            int64_t w;
            int64_t h;
        } rect;
    } data;
};

struct Color {
    int64_t r;
    int64_t g;
    int64_t b;
};

typedef struct Renderable_vtable {
    void (*render)(void* self, int64_t ctx);
    int64_t (*size)(void* self);
} Renderable_vtable;

struct Button {
    const char* label;
    void (*on_click)(void*);
};

int64_t Color_brighten(int64_t amount);
void Button_body(void);
void MainWindow_root(void);
int64_t helper(void);
void main(void);

int64_t Color_brighten(int64_t amount) {
    return (amount * 2);
}

void Button_body(void) {
    int64_t width = MAX_WIDTH;
}

static void Button_on_tap(void* ctx) {
    int64_t x = 1;
}

static void Button_on_swipe(void* ctx, int64_t direction) {
    int64_t d = direction;
}

void MainWindow_root(void) {
    const char* title = "REOX App";
}

void MainWindow_setup(void) {
    rx_app_t* app = rx_app_new();
    rx_app_run(app);
}

int64_t helper(void) {
    return 42;
}

void main(void) {
    Dimension width = MAX_WIDTH;
    int64_t height = MAX_HEIGHT;
    int64_t dir = 0;
    int64_t result = helper();
    int64_t bright = Color_brighten(10);
    Button_body();
    MainWindow_root();
    print(width);
    print(height);
    print(result);
    print(bright);
}

