// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <setjmp.h>
#include "reox_runtime.h"
#include "reox_nxrender_bridge.h"


static int64_t counter = 0;
static const char* app_name = "Calculator";
extern void println(const char* s);
extern const char* int_to_string(int64_t i);
extern const char* string_concat(const char* a, const char* b);
extern const char* str(const char* s);

int64_t test_else_if(void);
void increment(void);
const char* greet(const char* name);
int64_t main(void);

int64_t test_else_if(void) {
    int64_t x = 5;
    if ((x > 10)) {
        return 3;
    } else if ((x > 3)) {
        return 2;
    } else {
        return 1;
    }
}

void increment(void) {
    counter = (counter + 1);
}

const char* greet(const char* name) {
    return string_concat(string_concat("Hello, ", str(name)), "!");
}

int64_t main(void) {
    int64_t result = test_else_if();
    println(int_to_string(result));
    increment();
    increment();
    println(int_to_string(counter));
    println(app_name);
    const char* msg = greet("REOX");
    println(msg);
    return 0;
}

