// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <setjmp.h>
#include "reox_runtime.h"
#include "reox_nxrender_bridge.h"


int64_t main(void);

int64_t main(void) {
    while (condition_var) {
        auto x = 1;
        auto y = 2;
        y = (y + 1);
    }
    return 0;
}

