// Generated by REOX Compiler
// Do not edit manually

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <setjmp.h>
#include "reox_runtime.h"
#include "reox_nxrender_bridge.h"


int64_t main(void);

int64_t main(void) {
    int64_t x = 10;
    x = 99;
    return x;
}

