// REOX Compiler - Code Generator
// Generates C code from typed AST
// Zero external dependencies

use crate::parser::{
    Ast, Decl, Stmt, Expr, Literal, BinOp, UnaryOp, CompoundOp,
    FnDecl, StructDecl, ExternDecl, Block, Type, LetStmt,
    ReturnStmt, IfStmt, WhileStmt, ForStmt, GuardStmt, DeferStmt,
    TryCatchStmt, ThrowStmt,
    VariantDecl, ProtocolDecl, ExtensionDecl, LayerDecl, PanelDecl,
    ConstDecl, TypealiasDecl,
};
use std::io::{self, Write};

/// Code generator state
pub struct CodeGen {
    output: String,
    indent: usize,
    defer_stack: Vec<Block>,
    closure_counter: usize,
    closure_defs: String,
}

impl CodeGen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            defer_stack: Vec::new(),
            closure_counter: 0,
            closure_defs: String::new(),
        }
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn emit_line(&mut self, s: &str) {
        self.emit_indent();
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn emit_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn indent(&mut self) {
        self.indent += 1;
    }

    fn dedent(&mut self) {
        if self.indent > 0 {
            self.indent -= 1;
        }
    }

    /// Generate C code from AST
    pub fn generate(&mut self, ast: &Ast) -> String {
        // Emit header
        self.emit_line("// Generated by REOX Compiler");
        self.emit_line("// Do not edit manually");
        self.emit_line("");
        self.emit_line("#include <stdio.h>");
        self.emit_line("#include <stdlib.h>");
        self.emit_line("#include <stdint.h>");
        self.emit_line("#include <stdbool.h>");
        self.emit_line("#include <string.h>");
        self.emit_line("#include \"reox_runtime.h\"");
        self.emit_line("#include \"reox_nxrender_bridge.h\"");  // NXRender integration
        self.emit_line("");

        // Forward declarations for structs and variants
        for decl in &ast.declarations {
            match decl {
                Decl::Struct(s) => self.emit_line(&format!("typedef struct {} {};", s.name, s.name)),
                Decl::Variant(v) => self.emit_line(&format!("typedef struct {0} {0};", v.name)),
                Decl::Layer(l) => self.emit_line(&format!("typedef struct {0} {0};", l.name)),
                _ => {}
            }
        }
        self.emit_line("");

        // Generate typealias
        for decl in &ast.declarations {
            if let Decl::Typealias(t) = decl {
                self.gen_typealias(t);
            }
        }

        // Generate const
        for decl in &ast.declarations {
            if let Decl::Const(c) = decl {
                self.gen_const(c);
            }
        }

        // Generate variant (tagged union)
        for decl in &ast.declarations {
            if let Decl::Variant(v) = decl {
                self.gen_variant(v);
                self.emit_line("");
            }
        }

        // Generate struct definitions
        for decl in &ast.declarations {
            if let Decl::Struct(s) = decl {
                self.gen_struct(s);
                self.emit_line("");
            }
        }

        // Generate protocol (vtable)
        for decl in &ast.declarations {
            if let Decl::Protocol(p) = decl {
                self.gen_protocol(p);
                self.emit_line("");
            }
        }

        // Generate layer structs
        for decl in &ast.declarations {
            if let Decl::Layer(l) = decl {
                self.gen_layer_struct(l);
                self.emit_line("");
            }
        }

        // Generate extern declarations
        for decl in &ast.declarations {
            if let Decl::Extern(e) = decl {
                self.gen_extern(e);
            }
        }
        if ast.declarations.iter().any(|d| matches!(d, Decl::Extern(_))) {
            self.emit_line("");
        }

        // Generate function prototypes (including extension methods)
        for decl in &ast.declarations {
            match decl {
                Decl::Function(f) => self.gen_fn_prototype(f),
                Decl::Extension(ext) => {
                    for method in &ext.methods {
                        let mangled_name = format!("{}_{}", ext.target, method.name);
                        self.gen_fn_prototype_named(&mangled_name, method);
                    }
                }
                Decl::Layer(l) => {
                    for method in &l.methods {
                        let mangled_name = format!("{}_{}", l.name, method.name);
                        self.gen_fn_prototype_named(&mangled_name, method);
                    }
                }
                Decl::Panel(p) => {
                    for method in &p.methods {
                        let mangled_name = format!("{}_{}", p.name, method.name);
                        self.gen_fn_prototype_named(&mangled_name, method);
                    }
                }
                _ => {}
            }
        }
        self.emit_line("");

        // Emit closure static functions (generated during expression codegen)
        if !self.closure_defs.is_empty() {
            self.emit(&self.closure_defs.clone());
            self.emit_line("");
        }

        // Generate function implementations
        for decl in &ast.declarations {
            match decl {
                Decl::Function(f) => {
                    self.gen_function(f);
                    self.emit_line("");
                }
                Decl::Extension(ext) => {
                    self.gen_extension(ext);
                }
                Decl::Layer(l) => {
                    self.gen_layer_methods(l);
                }
                Decl::Panel(p) => {
                    self.gen_panel(p);
                    self.emit_line("");
                }
                _ => {}
            }
        }

        self.output.clone()
    }

    fn gen_struct(&mut self, s: &StructDecl) {
        self.emit_line(&format!("struct {} {{", s.name));
        self.indent();
        for field in &s.fields {
            let c_type = self.type_to_c(&field.ty);
            self.emit_line(&format!("{} {};", c_type, field.name));
        }
        self.dedent();
        self.emit_line("};");
    }

    fn gen_extern(&mut self, e: &ExternDecl) {
        let ret_type = e.return_type.as_ref()
            .map(|t| self.type_to_c(t))
            .unwrap_or_else(|| "void".to_string());

        let params: Vec<String> = e.params.iter()
            .map(|p| format!("{} {}", self.type_to_c(&p.ty), p.name))
            .collect();

        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };

        self.emit_line(&format!("extern {} {}({});", ret_type, e.name, params_str));
    }

    fn gen_fn_prototype(&mut self, f: &FnDecl) {
        let ret_type = f.return_type.as_ref()
            .map(|t| self.type_to_c(t))
            .unwrap_or_else(|| "void".to_string());

        let params: Vec<String> = f.params.iter()
            .map(|p| format!("{} {}", self.type_to_c(&p.ty), p.name))
            .collect();

        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };

        self.emit_line(&format!("{} {}({});", ret_type, f.name, params_str));
    }

    fn gen_fn_prototype_named(&mut self, name: &str, f: &FnDecl) {
        let ret_type = f.return_type.as_ref()
            .map(|t| self.type_to_c(t))
            .unwrap_or_else(|| "void".to_string());

        let params: Vec<String> = f.params.iter()
            .map(|p| format!("{} {}", self.type_to_c(&p.ty), p.name))
            .collect();

        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };

        self.emit_line(&format!("{} {}({});", ret_type, name, params_str));
    }

    fn gen_variant(&mut self, v: &VariantDecl) {
        // Emit C enum for tag
        self.emit_line(&format!("typedef enum {{"));
        self.indent();
        for (i, case) in v.cases.iter().enumerate() {
            let suffix = if i < v.cases.len() - 1 { "," } else { "" };
            self.emit_line(&format!("{}_{}{}", v.name.to_uppercase(), case.name.to_uppercase(), suffix));
        }
        self.dedent();
        self.emit_line(&format!("}} {}_Tag;", v.name));
        self.emit_line("");

        // Emit tagged union struct
        self.emit_line(&format!("struct {} {{", v.name));
        self.indent();
        self.emit_line(&format!("{}_Tag tag;", v.name));

        // If any case has fields, emit a union
        let has_payload = v.cases.iter().any(|c| !c.fields.is_empty());
        if has_payload {
            self.emit_line("union {");
            self.indent();
            for case in &v.cases {
                if !case.fields.is_empty() {
                    self.emit_line("struct {");
                    self.indent();
                    for field in &case.fields {
                        let c_type = self.type_to_c(&field.ty);
                        self.emit_line(&format!("{} {};", c_type, field.name));
                    }
                    self.dedent();
                    self.emit_line(&format!("}} {};", case.name.to_lowercase()));
                }
            }
            self.dedent();
            self.emit_line("} data;");
        }

        self.dedent();
        self.emit_line("};");
    }

    fn gen_protocol(&mut self, p: &ProtocolDecl) {
        // Protocol → vtable struct of function pointers
        self.emit_line(&format!("typedef struct {}_vtable {{", p.name));
        self.indent();
        for method in &p.methods {
            let ret_type = method.return_type.as_ref()
                .map(|t| self.type_to_c(t))
                .unwrap_or_else(|| "void".to_string());

            let mut params: Vec<String> = vec!["void* self".to_string()];
            for param in &method.params {
                params.push(format!("{} {}", self.type_to_c(&param.ty), param.name));
            }

            self.emit_line(&format!("{} (*{})({});", ret_type, method.name, params.join(", ")));
        }
        self.dedent();
        self.emit_line(&format!("}} {}_vtable;", p.name));
    }

    fn gen_extension(&mut self, ext: &ExtensionDecl) {
        for method in &ext.methods {
            let mangled_name = format!("{}_{}", ext.target, method.name);
            self.gen_function_named(&mangled_name, method);
            self.emit_line("");
        }
    }

    fn gen_layer_struct(&mut self, l: &LayerDecl) {
        self.emit_line(&format!("struct {} {{", l.name));
        self.indent();
        for field in &l.fields {
            let c_type = self.type_to_c(&field.ty);
            self.emit_line(&format!("{} {};", c_type, field.name));
        }
        // Signal callback slots
        for signal in &l.signals {
            self.emit_line(&format!("void (*{})(void*);", signal.name));
        }
        self.dedent();
        self.emit_line("};");
    }

    fn gen_layer_methods(&mut self, l: &LayerDecl) {
        for method in &l.methods {
            let mangled_name = format!("{}_{}", l.name, method.name);
            self.gen_function_named(&mangled_name, method);
            self.emit_line("");
        }
    }

    fn gen_panel(&mut self, p: &PanelDecl) {
        // Generate panel methods
        for method in &p.methods {
            let mangled_name = format!("{}_{}", p.name, method.name);
            self.gen_function_named(&mangled_name, method);
            self.emit_line("");
        }

        // Generate panel setup function
        self.emit_line(&format!("void {}_setup(void) {{", p.name));
        self.indent();
        self.emit_line("rx_app_t* app = rx_app_new();");

        // Emit property assignments
        for (key, value) in &p.properties {
            match key.as_str() {
                "title" => {
                    self.emit_indent();
                    self.emit("rx_app_set_title(app, ");
                    self.gen_expr(value);
                    self.emit(");\n");
                }
                "size" => {
                    self.emit_indent();
                    self.emit("rx_app_set_size(app, ");
                    self.gen_expr(value);
                    self.emit(");\n");
                }
                _ => {
                    self.emit_line(&format!("/* panel property: {} */", key));
                }
            }
        }

        self.emit_line("rx_app_run(app);");
        self.dedent();
        self.emit_line("}");
    }

    fn gen_const(&mut self, c: &ConstDecl) {
        let c_type = c.ty.as_ref()
            .map(|t| self.type_to_c(t))
            .unwrap_or_else(|| "const int64_t".to_string());

        self.emit_indent();
        self.emit(&format!("static const {} {} = ", c_type, c.name));
        self.gen_expr(&c.value);
        self.emit(";\n");
    }

    fn gen_typealias(&mut self, t: &TypealiasDecl) {
        let target_c = self.type_to_c(&t.target);
        self.emit_line(&format!("typedef {} {};", target_c, t.name));
    }

    fn gen_function_named(&mut self, name: &str, f: &FnDecl) {
        self.defer_stack.clear();

        let ret_type = f.return_type.as_ref()
            .map(|t| self.type_to_c(t))
            .unwrap_or_else(|| "void".to_string());

        let params: Vec<String> = f.params.iter()
            .map(|p| format!("{} {}", self.type_to_c(&p.ty), p.name))
            .collect();

        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };

        self.emit_line(&format!("{} {}({}) {{", ret_type, name, params_str));
        self.indent();
        self.gen_block(&f.body);

        if !self.defer_stack.is_empty() {
            self.emit_deferred_cleanup();
        }

        self.dedent();
        self.emit_line("}");
    }

    fn gen_function(&mut self, f: &FnDecl) {
        // Clear defer stack for new function
        self.defer_stack.clear();
        
        let ret_type = f.return_type.as_ref()
            .map(|t| self.type_to_c(t))
            .unwrap_or_else(|| "void".to_string());

        let params: Vec<String> = f.params.iter()
            .map(|p| format!("{} {}", self.type_to_c(&p.ty), p.name))
            .collect();

        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };

        self.emit_line(&format!("{} {}({}) {{", ret_type, f.name, params_str));
        self.indent();
        self.gen_block(&f.body);
        
        // Emit any remaining deferred cleanup at function end (for void functions)
        if !self.defer_stack.is_empty() {
            self.emit_deferred_cleanup();
        }
        
        self.dedent();
        self.emit_line("}");
    }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.statements {
            self.gen_statement(stmt);
        }
    }

    fn gen_statement(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(l) => self.gen_let(l),
            Stmt::Return(r) => self.gen_return(r),
            Stmt::If(i) => self.gen_if(i),
            Stmt::While(w) => self.gen_while(w),
            Stmt::For(f) => self.gen_for(f),
            Stmt::Expr(e) => {
                self.emit_indent();
                self.gen_expr(e);
                self.emit(";\n");
            }
            Stmt::Block(b) => {
                self.emit_line("{");
                self.indent();
                self.gen_block(b);
                self.dedent();
                self.emit_line("}");
            }
            Stmt::Break(_) => self.emit_line("break;"),
            Stmt::Continue(_) => self.emit_line("continue;"),
            // Swift/C++ style statements
            Stmt::Guard(g) => self.gen_guard(g),
            Stmt::Defer(d) => self.gen_defer(d),
            Stmt::TryCatch(t) => self.gen_try_catch(t),
            Stmt::Throw(t) => self.gen_throw(t),
        }
    }
    
    fn gen_guard(&mut self, g: &GuardStmt) {
        // guard condition else { ... }
        // Translates to: if (!(condition)) { ... }
        self.emit_indent();
        self.emit("if (!(");
        self.gen_expr(&g.condition);
        self.emit(")) {\n");
        self.indent();
        self.gen_block(&g.else_block);
        self.dedent();
        self.emit_line("}");
    }
    
    fn gen_defer(&mut self, d: &DeferStmt) {
        // Push deferred block onto stack - will be emitted before returns
        self.defer_stack.push(d.body.clone());
    }
    
    fn emit_deferred_cleanup(&mut self) {
        // Emit all deferred blocks in reverse order (LIFO)
        let blocks: Vec<Block> = self.defer_stack.iter().rev().cloned().collect();
        for block in blocks {
            self.emit_line("/* defer cleanup */");
            self.emit_line("{");
            self.indent();
            self.gen_block(&block);
            self.dedent();
            self.emit_line("}");
        }
    }
    
    fn gen_try_catch(&mut self, t: &TryCatchStmt) {
        // C doesn't have try/catch - emit as comments for now
        self.emit_line("/* try block */");
        self.emit_line("{");
        self.indent();
        self.gen_block(&t.try_block);
        self.dedent();
        self.emit_line("}");
        self.emit_line("/* catch block */");
        self.emit_line("{");
        self.indent();
        if let Some(var) = &t.catch_var {
            self.emit_line(&format!("/* error in {} */", var));
        }
        self.gen_block(&t.catch_block);
        self.dedent();
        self.emit_line("}");
    }
    
    fn gen_throw(&mut self, t: &ThrowStmt) {
        // C doesn't have throw - emit as comment + abort for now
        self.emit_indent();
        self.emit("/* throw */ abort(); /* ");
        self.gen_expr(&t.value);
        self.emit(" */\n");
    }

    fn gen_let(&mut self, l: &LetStmt) {
        let c_type = l.ty.as_ref()
            .map(|t| self.type_to_c(t))
            .unwrap_or_else(|| "auto".to_string()); // C23 auto or infer from init

        self.emit_indent();
        self.emit(&format!("{} {}", c_type, l.name));

        if let Some(init) = &l.init {
            self.emit(" = ");
            self.gen_expr(init);
        }

        self.emit(";\n");
    }

    fn gen_return(&mut self, r: &ReturnStmt) {
        // Emit deferred cleanup before return (in reverse order)
        if !self.defer_stack.is_empty() {
            self.emit_deferred_cleanup();
        }
        
        self.emit_indent();
        if let Some(value) = &r.value {
            self.emit("return ");
            self.gen_expr(value);
            self.emit(";\n");
        } else {
            self.emit("return;\n");
        }
    }

    fn gen_if(&mut self, i: &IfStmt) {
        self.emit_indent();
        self.emit("if (");
        self.gen_expr(&i.condition);
        self.emit(") {\n");
        self.indent();
        self.gen_block(&i.then_block);
        self.dedent();

        if let Some(else_block) = &i.else_block {
            self.emit_line("} else {");
            self.indent();
            self.gen_block(else_block);
            self.dedent();
        }

        self.emit_line("}");
    }

    fn gen_while(&mut self, w: &WhileStmt) {
        self.emit_indent();
        self.emit("while (");
        self.gen_expr(&w.condition);
        self.emit(") {\n");
        self.indent();
        self.gen_block(&w.body);
        self.dedent();
        self.emit_line("}");
    }

    fn gen_for(&mut self, f: &ForStmt) {
        match &f.iterable {
            Expr::Range(start, end, _) => {
                // Optimized C loop: for (int64_t i = start; i <= end; ++i)
                self.emit_indent();
                self.emit(&format!("for (int64_t {} = ", f.var));
                self.gen_expr(start);
                self.emit(&format!("; {} <= ", f.var));
                self.gen_expr(end);
                self.emit(&format!("; ++{}) {{\n", f.var));
                self.indent();
                self.gen_block(&f.body);
                self.dedent();
                self.emit_line("}");
            }
            _ => {
                // Default array iteration (simplified for C)
                // Assuming iterable is an array pointer or similar convention
                // This would typically rely on a runtime iterator or Array struct in C
                self.emit_indent();
                // Create unique iterator name
                let iter_name = format!("_iter_{}", f.var);
                self.emit(&format!("array_t* {} = ", iter_name));
                self.gen_expr(&f.iterable);
                self.emit(";\n");
                
                self.emit_indent();
                self.emit(&format!("for (int64_t _i = 0; _i < {}->length; ++_i) {{\n", iter_name));
                self.indent();
                self.emit_indent();
                // Extract item
                self.emit(&format!("int64_t {} = {}->data[_i];\n", f.var, iter_name));
                self.gen_block(&f.body);
                self.dedent();
                self.emit_line("}");
            }
        }
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Literal(lit) => self.gen_literal(lit),
            Expr::Identifier(name, _) => self.emit(name),
            Expr::Binary(left, op, right, _) => {
                self.emit("(");
                self.gen_expr(left);
                self.emit(&format!(" {} ", self.binop_to_c(op)));
                self.gen_expr(right);
                self.emit(")");
            }
            Expr::Unary(op, operand, _) => {
                self.emit(self.unaryop_to_c(op));
                self.gen_expr(operand);
            }
            Expr::Call(callee, args, _) => {
                // Check for UI widget function calls
                if let Expr::Identifier(name, _) = callee.as_ref() {
                    match name.as_str() {
                        // UI Widget constructors -> emit reox FFI calls
                        "button" => {
                            self.emit("reox_button_create(");
                            for (i, arg) in args.iter().enumerate() {
                                if i > 0 { self.emit(", "); }
                                self.gen_expr(arg);
                            }
                            self.emit(")");
                            return;
                        }
                        "text" | "label" => {
                            self.emit("reox_label_create(");
                            for (i, arg) in args.iter().enumerate() {
                                if i > 0 { self.emit(", "); }
                                self.gen_expr(arg);
                            }
                            self.emit(")");
                            return;
                        }
                        "input" | "textfield" => {
                            self.emit("reox_textfield_create(");
                            for (i, arg) in args.iter().enumerate() {
                                if i > 0 { self.emit(", "); }
                                self.gen_expr(arg);
                            }
                            self.emit(")");
                            return;
                        }
                        "slider" => {
                            self.emit("reox_slider_create(");
                            for (i, arg) in args.iter().enumerate() {
                                if i > 0 { self.emit(", "); }
                                self.gen_expr(arg);
                            }
                            self.emit(")");
                            return;
                        }
                        "checkbox" => {
                            self.emit("reox_checkbox_create(");
                            for (i, arg) in args.iter().enumerate() {
                                if i > 0 { self.emit(", "); }
                                self.gen_expr(arg);
                            }
                            self.emit(")");
                            return;
                        }
                        "vstack" => {
                            self.emit("reox_vstack(");
                            if !args.is_empty() {
                                self.gen_expr(&args[0]);
                            } else {
                                self.emit("0");
                            }
                            self.emit(")");
                            return;
                        }
                        "hstack" => {
                            self.emit("reox_hstack(");
                            if !args.is_empty() {
                                self.gen_expr(&args[0]);
                            } else {
                                self.emit("0");
                            }
                            self.emit(")");
                            return;
                        }
                        "window" => {
                            self.emit("reox_window_create(");
                            for (i, arg) in args.iter().enumerate() {
                                if i > 0 { self.emit(", "); }
                                self.gen_expr(arg);
                            }
                            self.emit(")");
                            return;
                        }
                        // Theme colors -> emit directly
                        "color_primary" => { self.emit("(rx_color){0, 122, 255, 255}"); return; }
                        "color_secondary" => { self.emit("(rx_color){88, 86, 214, 255}"); return; }
                        "color_success" => { self.emit("(rx_color){52, 199, 89, 255}"); return; }
                        "color_warning" => { self.emit("(rx_color){255, 149, 0, 255}"); return; }
                        "color_danger" => { self.emit("(rx_color){255, 59, 48, 255}"); return; }
                        "color_background" => { self.emit("(rx_color){28, 28, 30, 255}"); return; }
                        "color_surface" => { self.emit("(rx_color){44, 44, 46, 255}"); return; }
                        "color_text" => { self.emit("(rx_color){255, 255, 255, 255}"); return; }
                        // Standard function - emit as-is
                        _ => {}
                    }
                }
                // Default: emit as regular function call
                self.gen_expr(callee);
                self.emit("(");
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.gen_expr(arg);
                }
                self.emit(")");
            }
            Expr::Member(obj, field, _) => {
                self.gen_expr(obj);
                self.emit(&format!(".{}", field));
            }
            Expr::Index(arr, idx, _) => {
                self.gen_expr(arr);
                self.emit("[");
                self.gen_expr(idx);
                self.emit("]");
            }
            Expr::Assign(target, value, _) => {
                self.gen_expr(target);
                self.emit(" = ");
                self.gen_expr(value);
            }
            Expr::StructLit(name, fields, _) => {
                self.emit(&format!("({}){{", name));
                for (i, (field_name, value)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.emit(&format!(".{} = ", field_name));
                    self.gen_expr(value);
                }
                self.emit("}");
            }
            Expr::ArrayLit(elements, _) => {
                self.emit("{");
                for (i, elem) in elements.iter().enumerate() {
                    if i > 0 {
                        self.emit(", ");
                    }
                    self.gen_expr(elem);
                }
                self.emit("}");
            }
            Expr::Match(scrutinee, arms, _) => {
                // Generate match as a series of if-else chains
                // For simple integer patterns, could use switch but if-else is more general
                self.emit("({\n");
                self.indent();
                
                // Store scrutinee in temporary variable
                self.emit_indent();
                self.emit("__auto_type _match_val = ");
                self.gen_expr(scrutinee);
                self.emit(";\n");
                
                // Default result variable
                self.emit_line("typeof(_match_val) _match_result = 0;");
                
                for (i, arm) in arms.iter().enumerate() {
                    self.emit_indent();
                    if i == 0 {
                        self.emit("if (");
                    } else {
                        self.emit("} else if (");
                    }
                    
                    // Generate pattern condition
                    match &arm.pattern {
                        crate::parser::Pattern::Literal(lit) => {
                            self.emit("_match_val == ");
                            self.gen_literal(lit);
                        }
                        crate::parser::Pattern::Identifier(name) => {
                            // Binding pattern - always matches
                            self.emit("1 /* bind ");
                            self.emit(name);
                            self.emit(" */");
                        }
                        crate::parser::Pattern::Wildcard => {
                            self.emit("1 /* wildcard */");
                        }
                    }
                    
                    self.emit(") {\n");
                    self.indent();
                    self.emit_indent();
                    self.emit("_match_result = ");
                    self.gen_expr(&arm.body);
                    self.emit(";\n");
                    self.dedent();
                }
                
                if !arms.is_empty() {
                    self.emit_line("}");
                }
                
                self.emit_line("_match_result;");
                self.dedent();
                self.emit_indent();
                self.emit("})");
            }
            // Swift/C++ style expressions
            Expr::CompoundAssign(target, op, value, _) => {
                self.gen_expr(target);
                self.emit(&format!(" {} ", self.compound_op_to_c(op)));
                self.gen_expr(value);
            }
            Expr::PreIncrement(operand, _) => {
                self.emit("++");
                self.gen_expr(operand);
            }
            Expr::PreDecrement(operand, _) => {
                self.emit("--");
                self.gen_expr(operand);
            }
            Expr::PostIncrement(operand, _) => {
                self.gen_expr(operand);
                self.emit("++");
            }
            Expr::PostDecrement(operand, _) => {
                self.gen_expr(operand);
                self.emit("--");
            }
            Expr::NullCoalesce(left, right, _) => {
                // C doesn't have ?? - use ternary conditional
                self.emit("((");
                self.gen_expr(left);
                self.emit(") ? (");
                self.gen_expr(left);
                self.emit(") : (");
                self.gen_expr(right);
                self.emit("))");
            }
            Expr::OptionalChain(obj, field, _) => {
                // C doesn't have ?. - emit regular member access
                self.gen_expr(obj);
                self.emit(&format!(".{}", field));
            }
            Expr::TrailingClosure(callee, body, _) => {
                // Emit callee call, then the closure body as a block
                self.gen_expr(callee);
                self.emit("; /* trailing closure: */\n");
                self.emit_line("{");
                self.indent();
                self.gen_block(body);
                self.dedent();
                self.emit_line("}");
            }
            Expr::Nil(_) => {
                self.emit("NULL");
            }
            Expr::Await(operand, _) => {
                // Emit await as rx_await() runtime call
                self.emit("rx_await(");
                self.gen_expr(operand);
                self.emit(")");
            }
            Expr::Range(start, end, _) => {
                // Runtime call to create array from range
                self.emit("rx_range(");
                self.gen_expr(start);
                self.emit(", ");
                self.gen_expr(end);
                self.emit(")");
            }
            Expr::Action(params, return_type, body, _) => {
                // Generate a static C function for this closure
                let closure_id = self.closure_counter;
                self.closure_counter += 1;
                let fn_name = format!("__rx_closure_{}", closure_id);

                let ret_c = return_type.as_ref()
                    .map(|t| self.type_to_c(t))
                    .unwrap_or_else(|| "void".to_string());

                let param_strs: Vec<String> = params.iter()
                    .map(|p| format!("{} {}", self.type_to_c(&p.ty), p.name))
                    .collect();
                let params_c = if param_strs.is_empty() {
                    "void".to_string()
                } else {
                    param_strs.join(", ")
                };

                // Generate the closure body into the deferred closure definitions buffer
                let mut body_gen = CodeGen::new();
                body_gen.indent = 1;
                body_gen.gen_block(body);

                self.closure_defs.push_str(&format!(
                    "static {} {}({}) {{\n{}}}\n\n",
                    ret_c, fn_name, params_c, body_gen.output
                ));

                // Emit the function pointer at the call site
                self.emit(&fn_name);
            }
        }
    }
    
    fn compound_op_to_c(&self, op: &CompoundOp) -> &'static str {
        match op {
            CompoundOp::AddEq => "+=",
            CompoundOp::SubEq => "-=",
            CompoundOp::MulEq => "*=",
            CompoundOp::DivEq => "/=",
            CompoundOp::ModEq => "%=",
        }
    }

    fn gen_literal(&mut self, lit: &Literal) {
        match lit {
            Literal::Int(n, _) => self.emit(&format!("{}", n)),
            Literal::Float(n, _) => self.emit(&format!("{:.15}", n)),
            Literal::String(s, _) => self.emit(&format!("\"{}\"", self.escape_string(s))),
            Literal::Bool(b, _) => self.emit(if *b { "true" } else { "false" }),
        }
    }

    fn escape_string(&self, s: &str) -> String {
        let mut result = String::new();
        for ch in s.chars() {
            match ch {
                '\n' => result.push_str("\\n"),
                '\t' => result.push_str("\\t"),
                '\r' => result.push_str("\\r"),
                '\\' => result.push_str("\\\\"),
                '"' => result.push_str("\\\""),
                '\0' => result.push_str("\\0"),
                _ => result.push(ch),
            }
        }
        result
    }

    fn type_to_c(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "int64_t".to_string(),
            Type::Float => "double".to_string(),
            Type::String => "const char*".to_string(),
            Type::Bool => "bool".to_string(),
            Type::Void => "void".to_string(),
            Type::Named(name) => name.clone(),
            Type::Array(inner) => format!("{}*", self.type_to_c(inner)),
            Type::Optional(inner) => format!("{}*", self.type_to_c(inner)),
            Type::Function(params, ret) => {
                let ret_c = self.type_to_c(ret);
                let params_c: Vec<String> = params.iter().map(|p| self.type_to_c(p)).collect();
                format!("{}(*)({})", ret_c, if params_c.is_empty() { "void".to_string() } else { params_c.join(", ") })
            }
            Type::Tuple(elems) => {
                format!("rx_tuple{}", elems.len())
            }
        }
    }

    fn binop_to_c(&self, op: &BinOp) -> &'static str {
        match op {
            BinOp::Add => "+",
            BinOp::Sub => "-",
            BinOp::Mul => "*",
            BinOp::Div => "/",
            BinOp::Mod => "%",
            BinOp::Eq => "==",
            BinOp::Ne => "!=",
            BinOp::Lt => "<",
            BinOp::Gt => ">",
            BinOp::Le => "<=",
            BinOp::Ge => ">=",
            BinOp::And => "&&",
            BinOp::Or => "||",
            BinOp::BitwiseAnd => "&",
            BinOp::BitwiseOr => "|",
            BinOp::BitwiseXor => "^",
            BinOp::ShiftLeft => "<<",
            BinOp::ShiftRight => ">>",
        }
    }

    fn unaryop_to_c(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Neg => "-",
            UnaryOp::Not => "!",
            UnaryOp::BitwiseNot => "~",
        }
    }
}

impl Default for CodeGen {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate C code from AST and write to file
pub fn generate(ast: &Ast, output_path: &str) -> io::Result<()> {
    let mut codegen = CodeGen::new();
    let c_code = codegen.generate(ast);

    let mut file = std::fs::File::create(output_path)?;
    file.write_all(c_code.as_bytes())?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::tokenize;
    use crate::parser::parse;

    #[test]
    fn test_simple_function() {
        let source = r#"
            fn main() {
                let x: int = 42;
                return 0;
            }
        "#;
        let tokens = tokenize(source).unwrap();
        let ast = parse(&tokens);
        let mut codegen = CodeGen::new();
        let output = codegen.generate(&ast);

        assert!(output.contains("void main(void)"));
        assert!(output.contains("int64_t x = 42"));
        assert!(output.contains("return 0"));
    }

    #[test]
    fn test_function_with_params() {
        let source = r#"
            fn add(a: int, b: int) -> int {
                return a + b;
            }
        "#;
        let tokens = tokenize(source).unwrap();
        let ast = parse(&tokens);
        let mut codegen = CodeGen::new();
        let output = codegen.generate(&ast);

        assert!(output.contains("int64_t add(int64_t a, int64_t b)"));
        assert!(output.contains("return (a + b)"));
    }

    #[test]
    fn test_struct() {
        let source = r#"
            struct Point {
                x: int,
                y: int
            }
        "#;
        let tokens = tokenize(source).unwrap();
        let ast = parse(&tokens);
        let mut codegen = CodeGen::new();
        let output = codegen.generate(&ast);

        assert!(output.contains("struct Point {"));
        assert!(output.contains("int64_t x;"));
        assert!(output.contains("int64_t y;"));
    }

    #[test]
    fn test_if_else() {
        let source = r#"
            fn check(x: int) -> int {
                if x > 0 {
                    return 1;
                } else {
                    return 0;
                }
            }
        "#;
        let tokens = tokenize(source).unwrap();
        let ast = parse(&tokens);
        let mut codegen = CodeGen::new();
        let output = codegen.generate(&ast);

        assert!(output.contains("if ((x > 0))"));
        assert!(output.contains("} else {"));
    }

    #[test]
    fn test_while_loop() {
        let source = r#"
            fn count() {
                let mut i: int = 0;
                while i < 10 {
                    i = i + 1;
                }
            }
        "#;
        let tokens = tokenize(source).unwrap();
        let ast = parse(&tokens);
        let mut codegen = CodeGen::new();
        let output = codegen.generate(&ast);

        assert!(output.contains("while ((i < 10))"));
    }
}
